name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup environment
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: NX Release Nightly
      #   run: |
      #     pnpm nx release prerelease --preid=nightly --verbose --yes --skip-commit
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags and commits
        run: git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
